export enum PostalCodeE {
  Grad_Zagreb_i_Zagrebačka = 10,
  Dubrovačko_Neretvanska = 20,
  Splitsko_Dalmatinska = 21,
  Šibensko_Kninska = 22,
  Zadarska = 23,
  Osječko_Baranjska = 31,
  Vukovarsko_Srijemska = 32,
  Virovitičko_Podravska = 33,
  Požeško_Slavonska = 34,
  Brodsko_Posavska = 35,
  Međimurska = 40,
  Varaždinska = 42,
  Bjelovarsko_Bilogorska = 43,
  Sisačko_Moslavačka = 44,
  Karlovačka = 47,
  Koprivničko_Križevačka = 48,
  Krapinsko_Zagorska = 49,
  Primorsko_Goranska = 51,
  Istarska = 52,
  Ličko_Senjska = 53,
}

export const postalCodes = [
  10,
  20,
  21,
  22,
  23,
  31,
  32,
  33,
  34,
  35,
  40,
  42,
  43,
  44,
  47,
  48,
  49,
  51,
  52,
  53,
];

export const postalDefault = {
  Grad_Zagreb_i_Zagrebačka: 0,
  Dubrovačko_Neretvanska: 0,
  Splitsko_Dalmatinska: 0,
  Šibensko_Kninska: 0,
  Zadarska: 0,
  Osječko_Baranjska: 0,
  Vukovarsko_Srijemska: 0,
  Virovitičko_Podravska: 0,
  Požeško_Slavonska: 0,
  Brodsko_Posavska: 0,
  Međimurska: 0,
  Varaždinska: 0,
  Bjelovarsko_Bilogorska: 0,
  Sisačko_Moslavačka: 0,
  Karlovačka: 0,
  Koprivničko_Križevačka: 0,
  Krapinsko_Zagorska: 0,
  Primorsko_Goranska: 0,
  Istarska: 0,
  Ličko_Senjska: 0,
};
